logging:
  level: "INFO"  # Уровень логирования для консоли
  file_level: "INFO"  # Уровень логирования для файлов
  log_dir: "logs"  # Директория для логов
  rotation: "15 MB"  # Размер файла лога перед ротацией
  retention: "30 days"  # Время хранения логов

parser:
  features: "html.parser" # Базовый движок парсера

api:
  telegram: "123456789:QWERTYUIASFGHJKL"  # Токен Telegram бота
  admins: [1234] # Суперпользователи бота.

database:
  url: "sqlite+aiosqlite:///var/database.db" # URL для db, sqlalchemy